---

- name: Set New Hostname {{New_Hostname}}
  command: bash -c "hostnamectl set-hostname {{New_Hostname}}"
  become: true
- name: Creates the index.php file
  template: src=50-cloud-init.yaml.j2 dest=/etc/netplan/50-cloud-init.yaml
  become: true
- name: Rebooting Server
  shell: shutdown -r now
  become: true

